# user_input = input("Enter a string: ")
# print("Length of the string:", len(user_input))
# user_input = input("Enter a string in lowercase: ")
# print("string in uppercase: ", user_input.upper())
# user_input = input("Enter a string in uppercase: ")
# print("string in lowercase: ", user_input.lower())
# user_input = input("Enter a string with a lovercase: ")
# print("Capitalized string: ", user_input.capitalize())
# # user_input = input("Enter a string: ")    #for method
# # print("counting substrings:", user_input.count("a"))
# user_input = input("Enter a string: ")
# print("Checking substring existence: ", user_input.find("u"))
# user_input = input("Enter a string: ")
# print("string reversal: ", user_input[::-1])
# user_input = input("Enter a string: ")
# print("splitting strings: ", user_input.split("="))
# user_input = input("Enter a string: ")
# print("joining strings: ", user_input.join("."))
# user_input = input("Enter a string with extra white spaces: ")
# print("Stripping Whitespace: ", user_input.strip())
